// Generates src/environments/environment.ts from .env (or from process.env in CI).
// thnx Claude for the script =)
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';

if (existsSync('.env')) {
  process.loadEnvFile('.env');
}

const { TMDB_API_URL = 'https://api.themoviedb.org/3', TMDB_ACCESS_TOKEN = '' } = process.env;

if (!TMDB_ACCESS_TOKEN) {
  console.warn('⚠ TMDB_ACCESS_TOKEN is empty. Copy .env.example to .env and set your token.');
}

const content = `// AUTO-GENERATED by scripts/set-env.mjs — do not edit, change .env instead.
export const environment = {
  tmdb: {
    baseUrl: '${TMDB_API_URL}',
    accessToken: '${TMDB_ACCESS_TOKEN}',
  },
};
`;

mkdirSync('src/environments', { recursive: true });
writeFileSync('src/environments/environment.ts', content);
console.log('✔ src/environments/environment.ts generated');
